"""
CervicalMeasureAssist
-----------------------
Usage:
- (Optional) Load a lateral cervical spine x-ray volume in Slicer.
- Open this module, choose the volume (optional), and create/select a Markups Fiducial.
- Place 8 points: C2_ant, C2_post, C2_center, C7_inf_ant, C7_inf_post, C7_sup_post, T1_ant, T1_post.
- Click "Update Measurements" to compute C2-C7 angle, T1 slope, and C2-C7 SVA.
- (Optional) Export a training sample (.npy/.nrrd/.json) with the same landmarks and measurements.
"""

import os
import sys

import slicer
from slicer.ScriptedLoadableModule import ScriptedLoadableModule, ScriptedLoadableModuleWidget, ScriptedLoadableModuleLogic, ScriptedLoadableModuleTest

_MODULE_DIR = os.path.dirname(os.path.abspath(__file__))
_lib_path = os.path.join(_MODULE_DIR, "lib")
if _lib_path not in sys.path:
    sys.path.insert(0, _lib_path)

import logic_angles_cervical
from cervical_assist_controller import AssistController
from cervical_measurement_sets import CERVICAL_SET, set_names
from ui_measure import MeasureUI
from ui_export import ExportUI
from ui_auto import AutoUI


class CervicalMeasureAssist(ScriptedLoadableModule):
    """Main module class required by Slicer."""

    def __init__(self, parent=None):
        ScriptedLoadableModule.__init__(self, parent)
        self.parent.title = "Cervical Measure Assist"
        self.parent.categories = ["Spine"]
        self.parent.dependencies = []
        self.parent.contributors = ["Generated by masaki39"]
        self.parent.helpText = (
            "Manually place 8 landmarks on a lateral cervical x-ray and compute "
            "C2-C7 angle, T1 slope, and C2-C7 SVA. Designed as a base for future "
            "AI-assisted keypoint proposals."
        )
        self.parent.acknowledgementText = "Developed as a scaffold for cervical parameter measurement."


class CervicalMeasureAssistWidget(ScriptedLoadableModuleWidget):
    """Widget setup and interactions."""

    def setup(self):
        ScriptedLoadableModuleWidget.setup(self)

        self.logic = CervicalMeasureAssistLogic()

        self.measureUI = MeasureUI(self.layout, set_names=set_names(), initial_set=CERVICAL_SET)
        self.exportUI = ExportUI(self.layout)
        self.autoUI = AutoUI(self.layout)

        self.controller = AssistController(self.measureUI, self.exportUI, self.autoUI, self.logic)

        self.layout.addStretch(1)

    def cleanup(self):
        self.controller.cleanup()


class CervicalMeasureAssistLogic(ScriptedLoadableModuleLogic):
    """Geometry computations for cervical parameters."""

    def compute_angles_from_points(self, points):
        return logic_angles_cervical.compute_cervical_measurements(points)


class CervicalMeasureAssistTest(ScriptedLoadableModuleTest):
    """Basic tests for the logic class."""

    def setUp(self):
        slicer.mrmlScene.Clear(0)

    def runTest(self):
        self.setUp()
        self.test_compute_angles_simple_geometry()

    def test_compute_angles_simple_geometry(self):
        """Use a simple synthetic configuration to validate cervical angles."""
        logic = CervicalMeasureAssistLogic()
        points = {
            "C2_ant":      (0.0, 0.0),
            "C2_post":     (1.0, 0.0),
            "C2_center":   (0.5, 0.0),
            "C7_inf_ant":  (0.0, 5.0),
            "C7_inf_post": (1.0, 5.0),
            "C7_sup_post": (1.0, 4.5),
            "T1_ant":      (0.0, 6.0),
            "T1_post":     (1.0, 6.0),
        }
        angles = logic.compute_angles_from_points(points)

        self.assertIn("C2C7_angle", angles)
        self.assertIn("T1S", angles)
        self.assertIn("C2C7_SVA", angles)
        self.assertTrue(abs(angles["C2C7_angle"] - 0.0) < 0.5)
        self.assertTrue(abs(angles["T1S"] - 0.0) < 0.5)
        self.assertTrue(abs(angles["C2C7_SVA"] - 0.0) < 0.1)
