"""
SagittalMeasureAssist
-----------------------
Usage:
- (Optional) Load a lateral spine x-ray volume in Slicer.
- Open this module, choose the volume (optional), and create/select a Markups Fiducial.
- Place 5 points in order (top to bottom): L1_ant, L1_post, S1_ant, S1_post, FH.
- Click "Update Measurements" to compute PI, PT, SS, and LL.
- (Optional) Export a training sample (.npy/.nrrd/.json) with the same landmarks and angles.

This module is a manual landmark-driven scaffold for future AI-assisted keypoint
suggestion. Geometry calculations are isolated in the Logic class so automated
detectors can be plugged in later.
"""

import os
import sys

import slicer
from slicer.ScriptedLoadableModule import ScriptedLoadableModule, ScriptedLoadableModuleWidget, ScriptedLoadableModuleLogic, ScriptedLoadableModuleTest

lib_path = os.path.join(os.path.dirname(__file__), "lib")
if lib_path not in sys.path:
    sys.path.insert(0, lib_path)

import logic_angles
from assist_controller import AssistController
from measurement_sets import PELVIC_SET, set_names
from ui_measure import MeasureUI
from ui_export import ExportUI
from ui_auto import AutoUI


class SagittalMeasureAssist(ScriptedLoadableModule):
    """Main module class required by Slicer."""

    def __init__(self, parent=None):
        ScriptedLoadableModule.__init__(self, parent)
        self.parent.title = "Sagittal Measure Assist"
        self.parent.categories = ["Spine"]
        self.parent.dependencies = []
        self.parent.contributors = ["Generated by masaki39"]
        self.parent.helpText = (
            "Manually place 5 landmarks on a lateral x-ray (FH, S1_ant, S1_post, "
            "L1_ant, L1_post) and compute PI, PT, SS, and LL. Designed as a base "
            "for future AI-assisted keypoint proposals."
        )
        self.parent.acknowledgementText = "Developed as a scaffold for sagittal parameter measurement."


class SagittalMeasureAssistWidget(ScriptedLoadableModuleWidget):
    """Widget setup and interactions."""

    def setup(self):
        ScriptedLoadableModuleWidget.setup(self)

        self.logic = SagittalMeasureAssistLogic()

        # UI sections
        self.measureUI = MeasureUI(self.layout, set_names=set_names(), initial_set=PELVIC_SET)
        self.exportUI = ExportUI(self.layout)
        self.autoUI = AutoUI(self.layout)

        # Wire interactions via controller (keeps this entrypoint slim)
        self.controller = AssistController(self.measureUI, self.exportUI, self.autoUI, self.logic)

        self.layout.addStretch(1)

    def cleanup(self):
        self.controller.cleanup()


class SagittalMeasureAssistLogic(ScriptedLoadableModuleLogic):
    """Geometry computations for sagittal parameters."""

    def compute_angles_from_points(self, points):
        return logic_angles.compute_angles_from_points(points)


class SagittalMeasureAssistTest(ScriptedLoadableModuleTest):
    """Basic tests for the logic class."""

    def setUp(self):
        slicer.mrmlScene.Clear(0)

    def runTest(self):
        self.setUp()
        self.test_compute_angles_simple_geometry()

    def test_compute_angles_simple_geometry(self):
        """
        Use a simple synthetic configuration to validate angles.
        """
        logic = SagittalMeasureAssistLogic()
        points = {
            "FH": (0.5, 2.0),
            "S1_ant": (0.0, 0.0),
            "S1_post": (1.0, 1.0),
            "L1_ant": (0.0, 1.0),
            "L1_post": (1.0, 2.0),
        }
        angles = logic.compute_angles_from_points(points)

        self.assertTrue(abs(angles["SS"] + 45.0) < 0.5)  # SS expected -45 (signed)
        self.assertTrue(abs(angles["LL"] - 0.0) < 0.5)
        self.assertTrue(abs(angles["PT"] - 0.0) < 0.5)
        self.assertTrue(abs(angles["PI"] - 45.0) < 0.5)
